services:
  - type: web
    name: kaiwen-yimeiji
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py --host 0.0.0.0 --port $PORT"
    autoDeploy: false
